### ISSUE TITLE
fp8 can not set pp>1

### ISSUE THREAD

**Issue by mdy666** [NVIDIA/TransformerEngine#1604]
**Your question**
use fp8 and set pp_size=4, it raise a error.

```bash
[before the start of training step] datetime: 2025-03-22 18:11:11
[rank0]: Traceback (most recent call last):
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/pretrain_gpt.py", line 319, in <module>
[rank0]:     pretrain(
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/training/training.py", line 417, in pretrain
[rank0]:     iteration, num_floating_point_operations_so_far = train(
[rank0]:                                                       ^^^^^^
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/training/training.py", line 1569, in train
[rank0]:     train_step(forward_step_func,
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/training/training.py", line 850, in train_step
[rank0]:     losses_reduced = forward_backward_func(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 1829, in forward_backward_pipelining_without_interleaving
[rank0]:     input_tensor_grad = backward_step(
[rank0]:                         ^^^^^^^^^^^^^^
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 368, in backward_step
[rank0]:     custom_backward(output_tensor[0], output_tensor_grad[0])
[rank0]:   File "/sharedata/mdy/code/repo/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 152, in custom_backward
[rank0]:     Variable._execution_engine.run_backward(
[rank0]:   File "/sharedata/mdy/miniforge/lib/python3.12/site-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/sharedata/mdy/miniforge/lib/python3.12/site-packages/transformer_engine/pytorch/module/linear.py", line 419, in backward
[rank0]:     ) = TransformerEngineBaseModule.grad_output_preprocess(
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/sharedata/mdy/miniforge/lib/python3.12/site-packages/transformer_engine/pytorch/module/base.py", line 882, in grad_output_preprocess
[rank0]:     grad_output_c, grad_output_t = fp8_cast_transpose_fused(
[rank0]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/sharedata/mdy/miniforge/lib/python3.12/site-packages/transformer_engine/pytorch/cpp_extensions/transpose.py", line 60, in fp8_cast_transpose_fused
[rank0]:     tex.fused_cast_transpose_noop(
[rank0]: RuntimeError: /TransformerEngine/transformer_engine/common/transpose/../util/rtc.h:63 in function launch: CUDA Error: invalid device context
```

**Comment by ksivaman** [comment]
Could you share your megatron-LM launch config/command?

**Comment by mdy666** [comment]
> Could you share your megatron-LM launch config/command?

If set pp_size = 1, it will not raise any error when use fp8.
I have try many versions like
```bash
CUDA 12.3 + torch2.5 + TE1.3 / TE2.1
CUDA 12.4 + torch2.4 + TE1.3 / TE2.1
CUDA 12.8 + torch2.5 + TE1.3 / TE2.1
```

this is the command
```bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
GPUS_PER_NODE=8
# Change for multinode config
MASTER_ADDR=localhost
MASTER_PORT=6000
NUM_NODES=1
NODE_RANK=0
WORLD_SIZE=$(($GPUS_PER_NODE*$NUM_NODES))

EXP_NAME=zb2p-dpsk-fp8
TENSORBOARD_DIR="./tensorboard/zb2h/${EXP_NAME}"
mkdir -p ${TENSORBOARD_DIR}

CHECKPOINT_PATH=/sharedata/mdy/models/mcore/mixtral/fa3+fp8
SAVE_PATH=/sharedata/mdy/models/mcore/mixtral/${EXP_NAME}

DATA_PATH="
/sharedata/mdy/data/pretrain/mixtral/fineweb_edu_zh_text_document
/sharedata/mdy/data/pretrain/mixtral/fineweb_edu_en_text_document
/sharedata/mdy/data/pretrain/mixtral/math220k_text_document"

DISTRIBUTED_ARGS=(
    --nproc_per_node $GPUS_PER_NODE 
    --nnodes $NUM_NODES 
    --node_rank $NODE_RANK
    --master_addr $MASTER_ADDR 
    --master_port $MASTER_PORT
)

MODEL_ARGS=(
    --use-mcore-models
    --disable-bias-linear
    --seq-length 4096
    --max-position-embeddings 32768
    --num-layers 32
    --hidden-size 4096
    --ffn-hidden-size 14336
    --num-attention-heads 32
    --init-method-std 0.01
    --attention-dropout 0.0
    --hidden-dropout 0.0
    --normalization RMSNorm
    --position-embedding-type rope
    --swiglu
    --untie-embeddings-and-output-weights
    --group-query-attention
    --num-query-groups 8
    --no-masked-softmax-fusion
    --no-position-embedding
    --rotary-base 10000


    --tokenizer-type HuggingFaceTokenizer
    --tokenizer-model /sharedata/mdy/models/SauerkrautLM-Mixtral-8x7B-Instruct

    --log-throughput
    --log-timers-to-tensorboard

    --attention-backend flash
    --fp8-format e4m3s

    --use-dist-ckpt
    --ckpt-fully-parallel-save
    --async-save

    --use-distributed-optimizer
    --use-precision-aware-optimizer
    --exp-avg-dtype fp16
    --exp-avg-sq-dtype fp16
    --main-grads-dtype bf16

    --seed 42
    --dataloader-type cyclic

    --overlap-param-gather
    --overlap-grad-reduce
)

MOE_ARGS=(
    # --num-experts 8
    # --moe-router-topk 2
    # --moe-router-load-balancing-type aux_loss
    # --moe-aux-loss-coeff 1e-2
    # --moe-grouped-gemm
    # --moe-token-dispatcher-type alltoall
    --overlap-param-gather
    --overlap-grad-reduce
)

DATA_ARGS=(
    --data-path $DATA_PATH 
    # --vocab-file $VOCAB_FILE 
    # --merge-file $MERGE_FILE 
    --split 1000,0,0
)

TRAINING_ARGS=(
    --micro-batch-size 2
    --global-batch-size 256
    --train-iters 5000
    --weight-decay 0.1 
    --adam-beta1 0.9 
    --adam-beta2 0.95 
    --init-method-std 0.006 
    --clip-grad 1.0 
    --bf16
    --lr 5e-4 
    --lr-decay-style cosine 
    --min-lr 5e-5
    --lr-warmup-fraction .1 
    --lr-decay-iters 4000
)

MODEL_PARALLEL_ARGS=(
    --tensor-model-parallel-size 1
    --pipeline-model-parallel-size 4
    # --num-layers-per-virtual-pipeline-stage 2
    # --expert-model-parallel-size 2
    --sequence-parallel
)

LOGGING_ARGS=(
    --log-interval 1
    # --eval-interval 1000 
    # --save-interval 5000
    # --save $SAVE_PATH
    # --load $CHECKPOINT_PATH 
    # --ckpt-step 500
    # --finetune
    # --eval-iters 10
    --tensorboard-dir $TENSORBOARD_DIR
    --wandb-project zh2p
    --wandb-exp-name $EXP_NAME
    --wandb-save-dir ./wandb
)

# if [ -n "${WANDB_API_KEY}" ]; then
#     LOGGING_ARGS+=(
#         --wandb-project ${WANDB_PROJECT:-"Mixtral"}
#         --wandb-exp-name ${WANDB_NAME:-"Mixtral_8x7B"}
#     )
# fi


torchrun ${DISTRIBUTED_ARGS[@]} pretrain_gpt.py \
    ${MODEL_ARGS[@]} \
    ${MOE_ARGS[@]} \
    ${DATA_ARGS[@]} \
    ${TRAINING_ARGS[@]} \
    ${MODEL_PARALLEL_ARGS[@]} \
    ${LOGGING_ARGS[@]}

```

**Comment by timmoon10** [comment]
This error message seems related to https://github.com/NVIDIA/TransformerEngine/pull/1952/files#r2227461418

**Comment by sbhavani** [comment]
I cannot reproduce this on current Transformer Engine. The failing path appears to match the CUDA driver context issue fixed by #1952, which is included in TE v2.7 and later.

Closing as not reproducible on current releases. Please reopen or file a new issue with an updated repro if this still occurs on TE >= v2.7.
