### ISSUE TITLE
fp8_model_init fails with MXFP8BlockScaling

### ISSUE THREAD

**Issue by MaciejBalaNV** [NVIDIA/TransformerEngine#1687]
**Describe the bug**

When `fp8_model_init` is used in combination with `MXFP8BlockScaling`, the TE modules in the network have `requires_grad=False` if we cast the network to `bfloat16` precision. If we set `requires_grad=True` manually, the optimizer step fails, but only when using `FusedAdam` from TE, standard Adam from PyTorch works. Still, `FusedAdam` has multiple important features we need to use.

**Steps/Code to reproduce bug**
On B200 system, with 25.03 NVIDIA PyTorch container (TE version '2.1.0+450146a') we can use this code:

```

import os
import sys
import argparse

import transformer_engine.pytorch as te
from transformer_engine.common.recipe import Format, DelayedScaling, MXFP8BlockScaling

import torch
import torch.distributed as dist
import torch.nn.functional as F
from torch import nn, optim

class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNet, self).__init__()
        self.fc1 = te.Linear(input_size, hidden_size)
        self.fc2 = te.Linear(hidden_size, output_size)
        self.fc3 = torch.nn.Linear(output_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.fc3(x)
        return x


def _parse_args(argv=None, namespace=None):
    parser = argparse.ArgumentParser(description="Toy example for debugging fully_shard()")
    parser.add_argument("--input-size", type=int, default=2048, help="Input size for the model")
    parser.add_argument("--hidden-size", type=int, default=2048, help="Hidden layer size")
    parser.add_argument("--output-size", type=int, default=2048, help="Output size for the model")
    parser.add_argument("--batch-size", type=int, default=2048, help="Output size for the model")
    parser.add_argument(
        "--fp8-init", action="store_true", default=False, help="Initialize primary weights in FP8."
    )
    parser.add_argument(
        "--mxfp8", action="store_true", default=False, help="Use MXFP8BlockScaling instead of DelayedScaling."
    )
    parser.add_argument(
        "--te-optim", action="store_true", default=False, help="Use FusedAdam from TE."
    )
    parser.add_argument(
        "--fix-requires-grad", action="store_true", default=False, help="Manually set requires_grad=True in the network."
    )
    parser.add_argument(
        "--iter", type=int, default=10, help="Number of iterations for forward pass"
    )
    parser.add_argument(
        "--dtype", type=str, default="bfloat16", help="Dtype for testing."
    )
    parser.add_argument("--seed", type=int, default=42, help="RNG seed.")
    args = parser.parse_args(argv, namespace)
    return args


def _train(args):
    assert "TORCHELASTIC_RUN_ID" in os.environ
    WORLD_RANK = int(os.getenv("RANK", "0"))
    WORLD_SIZE = int(os.getenv("WORLD_SIZE", "1"))
    LOCAL_RANK = int(os.getenv("LOCAL_RANK", "0"))
    LOCAL_SIZE = int(os.getenv("LOCAL_WORLD_SIZE", "1"))
    assert LOCAL_SIZE == WORLD_SIZE

    # Set device and initialize RNG states
    torch.cuda.set_device(WORLD_RANK)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed(args.seed)

    # Initialize torch.distributed global process group and get DP/TP groups
    dist_init_kwargs = {
        "backend": "nccl",
        "rank": WORLD_RANK,
        "world_size": WORLD_SIZE,
    }
    assert dist.is_nccl_available()
    dist.init_process_group(**dist_init_kwargs)
    device = torch.device(f"cuda:{LOCAL_RANK}")
    assert args.dtype in ["float32", "bfloat16", "float16"]
    dtype = {
        "float32": torch.float32,
        "float16": torch.float16,
        "bfloat16": torch.bfloat16,
    }[args.dtype]

    # FP8 Configuration
    fp8_recipe = MXFP8BlockScaling() if args.mxfp8 else DelayedScaling()

    if args.fp8_init:
        build_model_context_args = {}
        from transformer_engine.pytorch import fp8_model_init

        build_model_context = fp8_model_init
        build_model_context_args["enabled"] = True
        build_model_context_args["recipe"] = fp8_recipe

        # Build the model with the specified context
        with build_model_context(**build_model_context_args):
            model = SimpleNet(args.input_size, args.hidden_size, args.output_size)
    else:
        model = SimpleNet(args.input_size, args.hidden_size, args.output_size)
    model = model.to(device=device, dtype=dtype)

    if args.fix_requires_grad:
        for param in model.parameters():
            param.requires_grad = True
    param_dict = {pn: p for pn, p in model.named_parameters()}
    param_dict = {pn: p for pn, p in param_dict.items() if p.requires_grad}
    decay_params = [p for n, p in param_dict.items()]
    print(f"Param count: {sum(p.numel() for p in decay_params)}")

    if args.te_optim:
        optimizer = te.optimizers.FusedAdam(model.parameters(), lr=1e-3)
    else:
        optimizer = optim.Adam(model.parameters(), lr=1e-3)

    for iteration in range(args.iter):
        # Zero the parameter gradients
        optimizer.zero_grad()
        input_data = torch.randn(args.batch_size, args.input_size).to(device=device, dtype=dtype)
        with te.fp8_autocast(enabled=True, fp8_recipe=fp8_recipe):
            output = model(input_data)
        target = torch.randn(args.batch_size, args.output_size).to(device=device, dtype=dtype)
        loss = F.mse_loss(output, target)
        loss.backward()
        optimizer.step()
        if LOCAL_RANK == 0:
            print(f"Rank {LOCAL_RANK}: Iteration {iteration} completed.")

    dist.destroy_process_group()
    if LOCAL_RANK == 0:
        print(f"Rank {LOCAL_RANK}: Done...")
    return 0


if __name__ == "__main__":
    sys.exit(_train(_parse_args()))

```

The following command fails during the optimizer step with `RuntimeError: CUDA error: an illegal memory access was encountered`

```
torchrun --nproc_per_node=8 te_test.py --mxfp8 --te-optim --fp8-init --fix-requires-grad
```
**Expected behavior**

`requires_grad` shouldn't be set to `False` after changing the network's precision. `FusedAdam` shouldn't fail.

**Environment overview (please complete the following information)**

 - Environment location: B200 bare metal
 - Method of Transformer Engine install: Docker nvcr.io/nvidian/pytorch:25.03-py3

**Device details**
- GPU model: B200

**Comment by zhongbozhu** [comment]
I think mxfp8 + fp8_model_init is not supported yet. @kunlunl is adding support to DSv3 style blockwise scaling which just get merged last week. As for mxfp8, it will be a next step.

**Comment by ksivaman** [comment]
Could you share the reason behind this workflow as it seems to be counterintuitive to convert the model to high precision right after initializing with FP8 parameters.

I believe there are 2 root causes for this error:
1. When gradients are enabled, pytorch enforces consistency of `requires_grad` attribute for tensor inputs of a torch autograd function. TE relies on this feature for correctly propagating the `requires_grad` field when quantizing and dequantizing tensors, so this is typically not an issue. However, `model.to(...)` internally disables gradients via `torch.no_grad()` and thus `requires_grad` is not set for model params after being cast.
2. `__torch_dispatch__` (which TE uses for custom ops like `.to` for quantized tensors) also seems to never set `requires_grad`.

What I haven't looked at is why there is an issue with MXFP8 specifically after manually setting the gradient via the `--fix-requires-grad` option in your script.

I'm working on a fix that resolves this issue without the need to set `requires_grad` manually, but I'm still thinking if this is the correct approach.

**Note:** That being said, we would first need to complete #2055 that adds MXFP8 parameters support to Fused Adam. Without Fused Adam, MXFP8 + `fp8_model_init` support exists.

**Comment by ksivaman** [comment]
Closing as stale
