### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED when using FusedAttnBackend["F16_arbitrary_seqlen"]

### ISSUE THREAD

**Issue by optyang** [NVIDIA/TransformerEngine#341]
Hi,

The code runs into an error when executing `_run_dot_product_attention` in the test `test_dot_product_attention` [here](https://github.com/NVIDIA/TransformerEngine/blob/main/tests/pytorch/test_fused_attn.py#L51). I am using cuda 12.1 and cudnn 8.9.3.

The parameters I use: `batch_size=16`, `num_attention_heads=32`, `head_dim=64`. When `seq_len=1024` and `mask_type="causal"`, the backend `F16_arbitrary_seqlen` is called and the code ends up in the CUDNN_STATUS_NOT_SUPPORTED error. The detailed log is as follows (btw the script `benchmark_fused_attn.py` is available [here](https://github.com/optyang/TransformerEngine/blob/main/tests/pytorch/benchmark_fused_attn.py), but it is essentially just a variant of `test_dot_product_attention`):

```text
(cudnn893) [yangyang22@devgpu018.ftw1 ~/dev/transformer_engine/tests/pytorch]$ python benchmark_fused_attn.py --batch_size=16 --num_attention_heads=32 --seq_len=1024 --head_dim=64 --attn_mask_type="causal" --repetition_warmup=0 --repetition_benchmark=1

=====torch.float16, 16-1024-32-64, p=0.0, causal, repetition_warmup=0, repetition_benchmark=1=========================
Traceback (most recent call last):
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 133, in <module>
    benchmark_dot_product_attention(dtype, args.batch_size, model_config, args.repetition_warmup, args.repetition_benchmark)
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 47, in benchmark_dot_product_attention
    time_forward, time_backward = _run_dot_product_attention(dtype, bs, config, "FusedAttention", repetition_warmup, repetition_benchmark)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 106, in _run_dot_product_attention
    op = block(q, k, v)
         ^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 933, in forward
    return self.fused_attention(query_layer, key_layer, value_layer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 620, in forward
    output = FusedAttnFunc_qkvpacked.apply(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 425, in forward
    out, aux_ctx_tensors = fused_attn_fwd_qkvpacked(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/cpp_extensions/fused_attn.py", line 296, in fused_attn_fwd_qkvpacked
    output_tensors = tex.fused_attn_fwd_qkvpacked(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /home/yangyang22/dev/transformer_engine/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu:668 in function fused_attn_arbitrary_seqlen_fwd_impl: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED
```

It seems to me that `fused_attn_f16_arbitrary_seqlen.cu` [here](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu#L536-L670) is very similar to the code in `fused_mha_sample.cpp` in `cudnn-frontend` [here](https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/fused_mha_sample.cpp#L869-L990). I could run `fused_mha_sample.cpp` successfuly.

BTW, both backend `F16_max512_seqlen` and `F16_arbitrary_seqlen` fails with the same CUDNN_STATUS_NOT_SUPPORTED when `seq_len` is 32 (other parameters are the same as above), but they are fine when `seq_len` is 512/256/128/64. The mask_type (`no_mask` or `causal`) does not matter. The error log for `F16_max512_seqlen` is as follows:
```text
(cudnn893) [yangyang22@devgpu018.ftw1 ~/dev/transformer_engine/tests/pytorch]$ python benchmark_fused_attn.py --batch_size=16 --num_attention_heads=32 --seq_len=32 --head_dim=64 --attn_mask_type="causal" --repetition_warmup=0 --repetition_benchmark=1

=====torch.float16, 16-32-32-64, p=0.0, causal, repetition_warmup=0, repetition_benchmark=1=========================
Traceback (most recent call last):
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 133, in <module>
    benchmark_dot_product_attention(dtype, args.batch_size, model_config, args.repetition_warmup, args.repetition_benchmark)
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 47, in benchmark_dot_product_attention
    time_forward, time_backward = _run_dot_product_attention(dtype, bs, config, "FusedAttention", repetition_warmup, repetition_benchmark)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/dev/transformer_engine/tests/pytorch/benchmark_fused_attn.py", line 106, in _run_dot_product_attention
    op = block(q, k, v)
         ^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 933, in forward
    return self.fused_attention(query_layer, key_layer, value_layer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 620, in forward
    output = FusedAttnFunc_qkvpacked.apply(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/attention.py", line 425, in forward
    out, aux_ctx_tensors = fused_attn_fwd_qkvpacked(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages/transformer_engine/pytorch/cpp_extensions/fused_attn.py", line 296, in fused_attn_fwd_qkvpacked
    output_tensors = tex.fused_attn_fwd_qkvpacked(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /home/yangyang22/dev/transformer_engine/transformer_engine/common/fused_attn/fused_attn_f16_max512_seqlen.cu:830 in function fused_attn_max_512_fwd_impl: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED
```

**Comment by cyanguwa** [comment]
Hi @optyang ,

I tried b=16, h=32, d=64, s=1024, 'causal' with cuDNN 8.9.3.28 on an H100 node, and it ran fine. Could you please let me know more details about your run?

Also, I can confirm that s=32 doesn't work with arbitrary_seqlen backend of our fused attention, and I have filed a bug internally.

Our support matrix is: the max512_seqlen backend supports seqlen%64==0 for 8.9.1+, and the arbitrary_seqlen backend supports %64==0 for 8.9.1+ and %32==0 for 8.9.3+. I will add some checks and docs for this matrix in our code. Thanks for filing this issue.

Regards,
Charlene

**Comment by optyang** [comment]
Hi @cyanguwa,

Thank you for looking into it! 

The packages in my conda environment are as follows:
```text
(cudnn893) [yangyang22@devgpu018.ftw1 ~/dev/transformer_engine]$ conda list
# packages in environment at /home/yangyang22/local/miniconda3/envs/cudnn893:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
annotated-types           0.5.0                    pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0    anaconda
blas                      1.0                         mkl  
brotlipy                  0.7.0           py311h9bf148f_1002    pytorch-nightly
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.5.7        py311h06a4308_0  
cffi                      1.15.1          py311h9bf148f_3    pytorch-nightly
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cmake                     3.26.4               h96355d8_0  
cryptography              38.0.4          py311h46ebde7_0    pytorch-nightly
cuda-cccl                 12.2.53                       0    nvidia
cuda-command-line-tools   12.1.1                        0    nvidia
cuda-compiler             12.2.0                        0    nvidia
cuda-cudart               12.1.105                      0    nvidia
cuda-cudart-dev           12.1.105                      0    nvidia
cuda-cudart-static        12.1.105                      0    nvidia
cuda-cuobjdump            12.2.53                       0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-cupti-static         12.1.105                      0    nvidia
cuda-cuxxfilt             12.2.53                       0    nvidia
cuda-documentation        12.2.53                       0    nvidia
cuda-driver-dev           12.2.53                       0    nvidia
cuda-gdb                  12.2.53                       0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-libraries-dev        12.1.0                        0    nvidia
cuda-libraries-static     12.1.0                        0    nvidia
cuda-nsight               12.2.53                       0    nvidia
cuda-nsight-compute       12.2.0                        0    nvidia
cuda-nvcc                 12.2.91                       0    nvidia
cuda-nvdisasm             12.2.53                       0    nvidia
cuda-nvml-dev             12.2.81                       0    nvidia
cuda-nvprof               12.2.60                       0    nvidia
cuda-nvprune              12.2.53                       0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvrtc-dev            12.1.105                      0    nvidia
cuda-nvrtc-static         12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-nvvp                 12.2.60                       0    nvidia
cuda-opencl               12.2.53                       0    nvidia
cuda-opencl-dev           12.2.53                       0    nvidia
cuda-profiler-api         12.2.53                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-sanitizer-api        12.2.53                       0    nvidia
cuda-toolkit              12.1.0                        0    nvidia
cuda-tools                12.1.0                        0    nvidia
cuda-visual-tools         12.1.0                        0    nvidia
einops                    0.6.1                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0    anaconda
ffmpeg                    4.2.2                h20bf706_0  
filelock                  3.9.0                   py311_0    pytorch-nightly
flash-attn                2.0.0.post1              pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2023.6.0                 pypi_0    pypi
gds-tools                 1.7.0.149                     0    nvidia
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py311hc9b5ff0_0  
gnutls                    3.6.15               he1e5248_0  
idna                      3.4             py311h06a4308_0  
iniconfig                 1.1.1              pyhd3eb1b0_0    anaconda
intel-openmp              2021.4.0          h06a4308_3561  
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
krb5                      1.20.1               h143b758_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 12.1.0.26                     0    nvidia
libcublas-dev             12.1.0.26                     0    nvidia
libcublas-static          12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufft-dev              11.0.2.4                      0    nvidia
libcufft-static           11.0.2.4                      0    nvidia
libcufile                 1.7.0.149                     0    nvidia
libcufile-dev             1.7.0.149                     0    nvidia
libcufile-static          1.7.0.149                     0    nvidia
libcurand                 10.3.3.53                     0    nvidia
libcurand-dev             10.3.3.53                     0    nvidia
libcurand-static          10.3.3.53                     0    nvidia
libcurl                   8.1.1                h251f7ec_1  
libcusolver               11.4.4.55                     0    nvidia
libcusolver-dev           11.4.4.55                     0    nvidia
libcusolver-static        11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libcusparse-dev           12.0.2.55                     0    nvidia
libcusparse-static        12.0.2.55                     0    nvidia
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0    anaconda
libev                     4.33                 h7f8727e_1    anaconda
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libidn2                   2.3.4                h5eee18b_0  
libnghttp2                1.52.0               h2d74bed_1  
libnpp                    12.0.2.50                     0    nvidia
libnpp-dev                12.0.2.50                     0    nvidia
libnpp-static             12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libnvjpeg-dev             12.1.1.14                     0    nvidia
libnvjpeg-static          12.1.1.14                     0    nvidia
libnvvm-samples           12.1.105                      0    nvidia
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libuv                     1.44.2               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py311h9bf148f_0    pytorch-nightly
mkl_fft                   1.3.1           py311hc796f24_0    pytorch-nightly
mkl_random                1.2.2           py311hbba84a0_0    pytorch-nightly
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.2.1                   py311_0    pytorch-nightly
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.4           py311h06a4308_1  
ninja                     1.11.1                   pypi_0    pypi
nsight-compute            2023.2.0.16                   0    nvidia
numpy                     1.24.3          py311hc206e33_0  
numpy-base                1.24.3          py311hfd5febd_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   3.0.9                h7f8727e_0  
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pillow                    9.3.0           py311h3fd9d12_2    pytorch-nightly
pip                       23.1.2          py311h06a4308_0  
pluggy                    1.0.0           py311h06a4308_1  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  2.0.3                    pypi_0    pypi
pydantic-core             2.3.0                    pypi_0    pypi
pyopenssl                 23.0.0          py311h06a4308_0  
pysocks                   1.7.1                   py311_0    pytorch-nightly
pytest                    7.3.1           py311h06a4308_0  
python                    3.11.4               h955ad1f_0  
pytorch                   2.1.0.dev20230720 py3.11_cuda12.1_cudnn8.9.2_0    pytorch-nightly
pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
pyyaml                    6.0             py311h5eee18b_1  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1                  py311_0    pytorch-nightly
rhash                     1.4.3                hdbd6064_0  
setuptools                67.8.0          py311h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.11.1          py311h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
tomli                     1.2.2              pyhd3eb1b0_0    anaconda
torchaudio                2.1.0.dev20230720     py311_cu121    pytorch-nightly
torchtriton               2.1.0+9e3e10c5ed           py311    pytorch-nightly
torchvision               0.16.0.dev20230720     py311_cu121    pytorch-nightly
transformer-engine        0.12.0.dev0+26c114f          pypi_0    pypi
typing_extensions         4.6.3           py311h06a4308_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.14                 py311_0    pytorch-nightly
wheel                     0.38.4          py311h06a4308_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

I am using cudnn 8.9.3.28 by specifying the following variables in `_build_cmake` [here](https://github.com/NVIDIA/TransformerEngine/blob/main/setup.py#L343):
```text
f"-DCUDNN_INCLUDE_DIR=/home/yangyang22/dev/cudnn-linux-x86_64-8.9.3.28_cuda12-archive/include",
f"-DCUDNN_LIBRARY=/home/yangyang22/dev/cudnn-linux-x86_64-8.9.3.28_cuda12-archive/lib/libcudnn.so.8.9.3",
```

Installation is successful, and here is the log:
```text
(cudnn893) [yangyang22@devgpu018.ftw1 ~/dev/transformer_engine]$ python -m pip install .
Processing /home/yangyang22/dev/transformer_engine
  Preparing metadata (setup.py) ... done
Collecting pydantic (from transformer-engine==0.12.0.dev0+26c114f)
  Using cached pydantic-2.0.3-py3-none-any.whl (364 kB)
Requirement already satisfied: torch in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from transformer-engine==0.12.0.dev0+26c114f) (2.1.0.dev20230720)
Collecting flash-attn<=2.0.0.post1,>=1.0.6 (from transformer-engine==0.12.0.dev0+26c114f)
  Using cached flash_attn-2.0.0.post1-cp311-cp311-linux_x86_64.whl
Collecting einops (from flash-attn<=2.0.0.post1,>=1.0.6->transformer-engine==0.12.0.dev0+26c114f)
  Using cached einops-0.6.1-py3-none-any.whl (42 kB)
Requirement already satisfied: packaging in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from flash-attn<=2.0.0.post1,>=1.0.6->transformer-engine==0.12.0.dev0+26c114f) (23.1)
Collecting ninja (from flash-attn<=2.0.0.post1,>=1.0.6->transformer-engine==0.12.0.dev0+26c114f)
  Using cached ninja-1.11.1-py2.py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (145 kB)
Collecting annotated-types>=0.4.0 (from pydantic->transformer-engine==0.12.0.dev0+26c114f)
  Using cached annotated_types-0.5.0-py3-none-any.whl (11 kB)
Collecting pydantic-core==2.3.0 (from pydantic->transformer-engine==0.12.0.dev0+26c114f)
  Using cached pydantic_core-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from pydantic->transformer-engine==0.12.0.dev0+26c114f) (4.6.3)
Requirement already satisfied: filelock in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from torch->transformer-engine==0.12.0.dev0+26c114f) (3.9.0)
Requirement already satisfied: sympy in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from torch->transformer-engine==0.12.0.dev0+26c114f) (1.11.1)
Requirement already satisfied: networkx in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from torch->transformer-engine==0.12.0.dev0+26c114f) (2.8.4)
Collecting jinja2 (from torch->transformer-engine==0.12.0.dev0+26c114f)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting fsspec (from torch->transformer-engine==0.12.0.dev0+26c114f)
  Using cached fsspec-2023.6.0-py3-none-any.whl (163 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch->transformer-engine==0.12.0.dev0+26c114f)
  Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Requirement already satisfied: mpmath>=0.19 in /home/yangyang22/local/miniconda3/envs/cudnn893/lib/python3.11/site-packages (from sympy->torch->transformer-engine==0.12.0.dev0+26c114f) (1.2.1)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... done
  Created wheel for transformer-engine: filename=transformer_engine-0.12.0.dev0+26c114f-cp311-cp311-linux_x86_64.whl size=114705979 sha256=210cd2030919427178fd7483ac14f5ff45df33d010c3a489cec225c8011ce72d
  Stored in directory: /tmp/pip-ephem-wheel-cache-l654jre9/wheels/2c/39/f6/b05fbb6834890437fd2e348bb061f5da1e018bd99a1d47ae71
Successfully built transformer-engine
Installing collected packages: ninja, pydantic-core, MarkupSafe, fsspec, einops, annotated-types, pydantic, jinja2, flash-attn, transformer-engine
  Attempting uninstall: transformer-engine
    Found existing installation: transformer-engine 0.12.0.dev0+26c114f
    Can't uninstall 'transformer-engine'. No files were found to uninstall.
Successfully installed MarkupSafe-2.1.3 annotated-types-0.5.0 einops-0.6.1 flash-attn-2.0.0.post1 fsspec-2023.6.0 jinja2-3.1.2 ninja-1.11.1 pydantic-2.0.3 pydantic-core-2.3.0 transformer-engine-0.12.0.dev0+26c114f
```

Please kindly let me know what other details I could provide. Thank you!

Best,

Yang

**Comment by cyanguwa** [comment]
Hi @optyang,

Thanks for providing the details. Could you please double check if the transformer engine library is linked to the appropriate cuDNN library during runtime? e.g. `ldd /path/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so`. If not, could you please try `export LD_LIBRARY_PATH=/home/yangyang22/dev/cudnn-linux-x86_64-8.9.3.28_cuda12-archive/lib/:$LD_LIBRARY_PATH`?

Thanks,
Charlene

**Comment by optyang** [comment]
Hi @cyanguwa,

Thanks for the advice, but the error is still there...

```text
(cudnn893) [yangyang22@devgpu018.ftw1 ~/dev/transformer_engine/tests/pytorch]$ echo $LD_LIBRARY_PATH
/home/yangyang22/local/miniconda3/envs/cudnn893/lib/:/home/yangyang22/dev/cudnn-linux-x86_64-8.9.3.28_cuda12-archive/lib/:
```

**Comment by optyang** [comment]
I tried a different machine (aws cluster with a100). I also tried to install cudnn 8.9.2 by conda. But neither helps.

**Comment by cyanguwa** [comment]
Hi @optyang , sorry about the delay in following up. I can confirm that our internal bug regarding d=32 is still ongoing. With your latest experiment above, are you still having issues with d=32 or d=64 on the A100 node? Thanks!

**Comment by cyanguwa** [comment]
Closing the ticket for now. Hope the issue has been resolved. Please file reopen it or file a new one if the problem persists. Thanks!
